os: osx
language: node_js
node_js:
  - "8.10.0"

install: 
  # Install the code requirements
  bash ./_bin/make_install.sh

script:
# Runs unit tests
- bash ./_bin/make_test.sh
# Push cover to codeclimate
- bash ./_bin/make_coverage.sh