AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        HASH_KEY: !Ref HashKey
        STAGE: !Ref Stage
        DYNAMODB_TENANT_TABLE: !Ref TenantsTable
    Tags:
      AppNameTag: m-tenant
      DepartmentNameTag: mojomanyana
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      MaxAge: "'600'" 
Parameters:
  Stage:
    Type: String
    Default: "dev"
    Description: "Stage for this API (usualy you can use prod,dev,stage...) default is Dev"
  HashKey:
    Type: String
    Default: "121212121212hdhdhdhdhdhdhdhdhdh"
    Description: "Hash key for encoding/decoding JWT web token"
Resources:
  GetAllTenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.getAll
      CodeUri: ./dist
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                'Fn::GetAtt':
                  - TenantsTable
                  - Arn
      Events:
        ListTenants:
          Type: Api
          Properties:
            Path: /tenants/list
            Method: POST
  NewTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.create
      CodeUri: ./dist
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                'Fn::GetAtt':
                  - TenantsTable
                  - Arn
      Events:
        AddTenant:
          Type: Api
          Properties:
            Path: /tenants/create
            Method: POST
  GetSingleTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.getSingle
      CodeUri: ./dist
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                'Fn::GetAtt':
                  - TenantsTable
                  - Arn
      Events:
        AddTenant:
          Type: Api
          Properties:
            Path: /tenants/{tenantName}
            Method: GET
  TenantsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName:
        Fn::Join:
          - ""
          - - !Ref Stage 
            - "_m_tenant"
      AttributeDefinitions:
        - AttributeName: tenantName
          AttributeType: S
      KeySchema:
        - AttributeName: tenantName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2