AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
    Default: "Dev"
    Description: "Stage for this API (usualy you can use prod,dev,stage...) default is Dev"
  HashKey:
    Type: String
    Default: "7676fggd376fgxq76r21sss52r3"
    Description: "Hash key for encoding/decoding JWT web token"
  CorsOrigin:
    Type: String
    Default: "*"
    Description: "Cross-origin resource sharing (CORS) restriction for the event submission Web Api. Restrict to a single web site domain to only allow submiss"
Resources:
  GetTenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: dist/index.get
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /tenants
            Method: GET
